version: '3.7'
services:
    sql_server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: 'Senha_s@'
            ACCEPT_EULA: Y